# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
bases:
  - ../../base

# namespace to deploy all Resources to
namespace: ode-ckan-prod-ns

resources:
- secretprovider.yaml
- ingress.yaml
# (uncomment below to use workload identity)
# - serviceaccount.yaml

patchesStrategicMerge:
  - resources.yaml

# labels added to all Resources
commonLabels:
  env: prod

configMapGenerator:
  - name: ckan-env-vars
    behavior: merge
    envs: 
    - .env