# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
bases:
  - ../../base

# namespace to deploy all Resources to
namespace: ode-ckan-prod-ns

# resources:
# - secretprovider.yaml

# patchesStrategicMerge:
#   - secretconfig.yaml
#   - resources.yaml
#   - volumeclaim.yaml  

# labels added to all Resources
commonLabels:
  app: odeckan
  env: prod
