apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ode-ckan-secretprovider
spec:
  parameters:
    keyvaultName: odl-ckan-kv-prod-we
    # (uncomment below to use workload identity)
    # clientID: 96990a29-d8c8-4776-a20e-fccaed6e527b # Setting this to use workload identity
    objects: |
      array:
        - |
          objectName: CKAN-SQLALCHEMY-URL
          objectAlias: CKAN_SQLALCHEMY_URL
          objectType: secret
        - |
          objectName: CKAN-CLIENT-ID
          objectAlias: CKAN_CLIENT_ID
          objectType: secret
        - |
          objectName: CKAN-CLIENT-SECRET
          objectAlias: CKAN_CLIENT_SECRET
          objectType: secret
        - |
          objectName: CKAN-API-KEY
          objectAlias: CKAN_API_KEY
          objectType: secret
        - |
          objectName: CKAN-QUEUE-CONNECTIONSTRING
          objectAlias: CKAN_QUEUE_CONN_STRING
          objectType: secret
          objectName: CKAN-PROD-TLS
          objectAlias: CKAN_PROD_TLS
          objectType: secret
        - |
          objectName: CKAN-DATA-COM-TLS
          objectAlias: CKAN_DATA_COM_TLS
          objectType: secret
        - |
          objectName: CKAN-DATA-DK-TLS
          objectAlias: CKAN_DATA_DK_TLS
          objectType: secret
        - |
          objectName: CKAN-DATA-WWW-COM-TLS
          objectAlias: CKAN_DATA_WWW_COM_TLS
          objectType: secret
        - |
          objectName: CKAN-DATA-WWW-DK-TLS
          objectAlias: CKAN_DATA_WWW_DK_TLS
          objectType: secret
          
    resourceGroup: DataLake-k8s-ckan-rg-PROD
    subscriptionId: 4c231678-e100-4dd2-91cd-6aeb69e1dff8
    tenantId: 100b3c99-f3e2-4da0-9c8a-b9d345742c36
  provider: azure
  secretObjects:
  - data:
    - key: ode-ckan-pg-conn-string
      objectName: CKAN_SQLALCHEMY_URL
    secretName: ode-pg-secrets
    type: Opaque
  - data:
    - key: tls.key
      objectName: CKAN_PROD_TLS
    - key: tls.crt
      objectName: CKAN_PROD_TLS
    secretName: ode-ckan-prod-ingress-tls
    type: kubernetes.io/tls
  - data:
    - key: tls.key
      objectName: CKAN_DATA_COM_TLS
    - key: tls.crt
      objectName: CKAN_DATA_COM_TLS
    secretName: ode-ckan-data-com-ingress-tls
    type: kubernetes.io/tls
  - data:
    - key: tls.key
      objectName: CKAN_DATA_DK_TLS
    - key: tls.crt
      objectName: CKAN_DATA_DK_TLS
    secretName: ode-ckan-data-dk-ingress-tls
    type: kubernetes.io/tls
  - data:
    - key: tls.key
      objectName: CKAN_DATA_WWW_COM_TLS
    - key: tls.crt
      objectName: CKAN_DATA_WWW_COM_TLS
    secretName: ode-ckan-data-www-com-ingress-tls
    type: kubernetes.io/tls
  - data:
    - key: tls.key
      objectName: CKAN_DATA_WWW_DK_TLS
    - key: tls.crt
      objectName: CKAN_DATA_WWW_DK_TLS
    secretName: ode-ckan-data-www-dk-ingress-tls
    type: kubernetes.io/tls