apiVersion: v1
kind: Service
metadata:
  labels:
    app: ckan
  name: ckan
  namespace: odl-ckan-sandbox-ns
spec:
  ports:
    - name: ckan-service
      port: 5000
      targetPort: 5000
  selector:
    app: ckan
