apiVersion: v1
kind: Service
metadata:
  labels:
    app: datapusher
  name: datapusher
  namespace: odl-ckan-sandbox-ns
spec:
  ports:
    - name: datapusher-service
      port: 8800
      targetPort: 8800
  selector:
    app: datapusher
