apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: datapusher
  name: datapusher
  namespace: odl-ckan-sandbox-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapusher
  serviceName: datapusher-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: datapusher
    spec:
      containers:
        - image: clementmouchet/datapusher
          envFrom:
          - configMapRef:
              name: ckan-env-vars
          name: datapusher
          imagePullPolicy: Never
          ports:
            - containerPort: 8800
          resources: {}
      restartPolicy: Always
