apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
  namespace: odl-ckan-sandbox-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  serviceName: db-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: ckan-env-vars
          image: docker_db
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - ckan
          name: db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      restartPolicy: Always
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data
