apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: odl-ckan-sandbox-ns
spec:
  ports:
    - name: "redis-service"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
