apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: solr-data
  name: solr-data
  namespace: odl-ckan-sandbox-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
