---
apiVersion: v1
kind: Service
metadata:
  name: odeckan-service
  labels:
    app: odeckan
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: odeckan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odeckan
  name: odeckan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odeckan
  template:
    metadata:
      labels:
        app: odeckan
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: ckan-env-vars
          image: ode-ckan-image
          name: ode-ckan
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: client
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1000m
          # volumeMounts:
          #   - name: kvsecrets
          #     mountPath: /etc/ckan_secrets
          #     readOnly: true
      restartPolicy: Always
      # volumes:
      #   - name: kvsecrets
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: TBD-OVERLAY-secret-provider
      #       nodePublishSecretRef:
      #         name: kvcreds

