# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- solr.yaml

# namespace to deploy all Resources to
namespace: tbd-in-overlays

images:
- name: ode-solr-image
  newName: datalakek8sacrdev.azurecr.io/ckan/solr/ode-solr-image
  newTag: 8.11.1

commonLabels:
  app: odesolr
  env: tbd-in-overlays

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true