---
apiVersion: v1
kind: Service
metadata:
  name: odesolr-service
  labels:
    app: odesolr
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "https"
      port: 8983
      targetPort: 8983
  selector:
    app: odesolr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odesolr
spec:
  selector:
    matchLabels:
      app: odesolr
  serviceName: odesolr-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel #OrderedReady
  template:
    metadata:
      labels:
        app: odesolr
    spec:
      containers:
        - image: ode-solr-image
          name: ode-solr
          imagePullPolicy: Always
          ports:
            - containerPort: 8983
              name: socket
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          volumeMounts:
          - name: odesolr-data
            mountPath: /opt/solr/server/
            subPath: data
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: odesolr-data
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: ode-solr-sc
      resources:
        requests:
          storage: 64Gi