---
apiVersion: v1
kind: Service
metadata:
  name: odesolr-service
  labels:
    app: odesolr
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "https"
      port: 8983
      targetPort: 8983
  selector:
    app: odesolr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: odesolr
  name: odesolr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odesolr
  serviceName: odesolr-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: odesolr
    spec:
      containers:
        - image: ode-solr-image
          name: ode-solr
          imagePullPolicy: Never
          ports:
            - containerPort: 8983
          resources: {}
          volumeMounts:
            - mountPath: /opt/solr/server/solr/ckan/data
              name: solr-data
      restartPolicy: Always
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: solr-data
  name: solr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
