---
apiVersion: v1
kind: Service
metadata:
  name: odesolr-service
  labels:
    app: odesolr
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "https"
      port: 8983
      targetPort: 8983
  selector:
    app: odesolr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odesolr
spec:
  selector:
    matchLabels:
      app: odesolr
  serviceName: odesolr-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel #OrderedReady
  template:
    metadata:
      labels:
        app: odesolr
    spec:
      containers:
        - image: ode-solr-image
          name: ode-solr
          imagePullPolicy: Always
          command: 
            - /bin/sh
            - -c
            - sleep infinity
            - sudo cp -R /opt/solr/server/solr/configsets/_default /opt/solr/server/solr/configsets/ckan
            - solr-precreate ckan /opt/solr-current/server/solr/configsets
          ports:
            - containerPort: 8983
              name: socket
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          volumeMounts:
          - mountPath: /opt/solr/server/solr/configsets/ckan/
            name: odesolr-data
            subPath: server
            # ConfigSets
          - mountPath: /opt/solr/server/solr/configsets/currency.xml
            name: currency-xml
            subPath: currency.xml
          - mountPath: /opt/solr/server/solr/configsets/synonyms.txt
            name: synonyms-txt
            subPath: synonyms.txt
          - mountPath: /opt/solr/server/solr/configsets/stopwords.txt
            name: stopwords-txt
            subPath: stopwords.txt
          - mountPath: /opt/solr/server/solr/configsets/protwords.txt
            name: protwords-txt
            subPath: protwords.txt
          - mountPath: /opt/solr/server/solr/configsets/elevate.xml
            name: elevate-xml
            subPath: elevate.xml
            #Schema
          - mountPath: /opt/solr/server/solr/configsets/schema.solr8.xml
            name: schema-solr8-xml
            subPath: schema.solr8.xml
      restartPolicy: Always
      volumes:
      - name: ckan-secrets
      - name: currency-xml
        configMap:
          name: solr-config
          items:
            - key: currency-xml
              path: currency-xml
          defaultMode: 0744
      - name: elevate-xml
        configMap:
          name: solr-config
          items:
            - key: elevate-xml
              path: elevate-xml
          defaultMode: 0744
      - name: protwords-txt
        configMap:
          name: solr-config
          items:
            - key: protwords-txt
              path: protwords-txt
          defaultMode: 0744
      - name: stopwords-txt
        configMap:
          name: solr-config
          items:
            - key: stopwords-txt
              path: stopwords-txt
          defaultMode: 0744
      - name: synonyms-txt
        configMap:
          name: solr-config
          items:
            - key: synonyms-txt
              path: synonyms-txt
          defaultMode: 0744
      - name: schema-solr8-xml
        configMap:
          name: solr-config
          items:
            - key: schema.solr8-xml
              path: schema.solr8-xml
          defaultMode: 0744
      # Solr data
      - name: odesolr-data
        persistentVolumeClaim:
          claimName: odesolr-data-claim