---
apiVersion: v1
kind: Service
metadata:
  name: odesolr-service
  labels:
    app: odesolr
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "https"
      port: 8983
      targetPort: 8983
  selector:
    app: odesolr
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: odesolr
#   name: odesolr-data-claim-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odesolr
  name: odesolr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odesolr
  template:
    metadata:
      labels:
        app: odesolr
    spec:
      containers:
        - image: ode-solr-image
          name: ode-solr
          imagePullPolicy: Always
          ports:
            - containerPort: 8983
              name: socket
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
      #     volumeMounts:
      #     - mountPath: /opt/solr/server/solr/ckan/data
      #       name: odesolr-data      
      # volumes:
      #   - name: odesolr-data
      #     persistentVolumeClaim:
      #       claimName: odesolr-data-claim
      restartPolicy: Always
