---
apiVersion: v1
kind: Service
metadata:
  name: odlsolr-hs
  labels:
    app: odlsolr
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "https"
      port: 8983
      targetPort: 8983
  selector:
    app: odlsolr
---
apiVersion: v1
kind: Service
metadata:
  name: odlsolr-cs
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: odlsolr
spec:
  type: LoadBalancer
  ports:
    - port: 443
      name: https
      targetPort: 8983
  selector:
    app: odlsolr
  sessionAffinity: ClientIP
  sessionAffinityConfig: 
    clientIP:
      timeoutSeconds: 10800
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: odlsolr
  name: odlsolr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odlsolr
  serviceName: odlsolr-hs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: odlsolr
    spec:
      containers:
        - image: odl-solr-image
          name: odl-solr
          imagePullPolicy: Never
          ports:
            - containerPort: 8983
          resources: {}
          volumeMounts:
            - mountPath: /opt/solr/server/solr/ckan/data
              name: solr-data
      restartPolicy: Always
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: solr-data
  name: solr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
