apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odesolr
spec:
  volumeClaimTemplates:
  - metadata:
      name: odesolr-data # (1)
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: ode-solr-dev-ssd-zrs-sc
      resources:
        requests:
          storage: 32Gi