apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: odesolr
    env: dev
  name: odesolr-data-claim
  namespace: ode-ckan-dev-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: ode-solr-dev-ssd-zrs-sc