---
apiVersion: v1
kind: Service
metadata:
  name: odldatapusher-hs
  labels:
    app: odldatapusher
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "socket"
      port: 8800
      targetPort: 8800
  selector:
    app: odldatapusher
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: odldatapusher
  name: odldatapusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odldatapusher
  serviceName: odldatapusher-hs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: odldatapusher
    spec:
      containers:
        - image: odl-datapusher-image
          name: odl-datapusher
          imagePullPolicy: Never
          ports:
            - containerPort: 8800
          resources: {}
      restartPolicy: Always
