---
apiVersion: v1
kind: Service
metadata:
  name: odedatapusher-service
  labels:
    app: odedatapusher
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "socket"
      port: 8800
      targetPort: 8800
  selector:
    app: odedatapusher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odedatapusher
  name: odedatapusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odedatapusher
  template:
    metadata:
      labels:
        app: odedatapusher
    spec:
      containers:
        - image: ode-datapusher-image
          name: ode-datapusher
          imagePullPolicy: Never
          ports:
            - containerPort: 8800
              name: socket
              protocol: TCP
          startupProbe:
            failureThreshold: 840
            periodSeconds: 30
            tcpSocket:
              port: socket
          readinessProbe:
            initialDelaySeconds: 840
            periodSeconds: 30
            timeoutSeconds: 30
            tcpSocket:
              port: socket
          livenessProbe:
            initialDelaySeconds: 840
            periodSeconds: 60
            tcpSocket:
              port: socket 
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi 
      restartPolicy: Always
