---
apiVersion: v1
kind: Service
metadata:
  name: odedatapusher-service
  labels:
    app: odedatapusher
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "socket"
      port: 8800
      targetPort: 8800
  selector:
    app: odedatapusher
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: odedatapusher
  name: odedatapusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odedatapusher
  serviceName: odedatapusher-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: odedatapusher
    spec:
      containers:
        - image: ode-datapusher-image
          name: ode-datapusher
          imagePullPolicy: Never
          ports:
            - containerPort: 8800
          resources: {}
      restartPolicy: Always
