# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- datapusher.yaml

# namespace to deploy all Resources to
namespace: tbd-in-overlays

commonLabels:
  app: odedatapusher
  env: tbd-in-overlays

images:
- name: ode-datapusher-image
  newName: datalakek8sacrdev.azurecr.io/ckan/datapusher/ode-datapusher-image
  newTag: latest

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true