apiVersion: apps/v1
kind: Deployment
metadata:
  name: odeckan
spec:
  selector:
    matchLabels:
      app: odeckan
  template:
    spec:
      containers:
      - name: ode-ckan # (1)
        env:
        - name: CKAN_SQLALCHEMY_URL
          valueFrom:
            secretKeyRef:
              key: ode-ckan-dev-pg-conn-string
              name: ode-ckan-dev-secrets