apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odlckan
spec:
  template:
    spec:
      containers:
      - name: odl-ckan # (1)
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m