apiVersion: apps/v1
kind: Deployment
metadata:
  name: odeckan
spec:
  selector:
    matchLabels:
      app: odeckan
  template:
    spec:
      serviceAccount: ode-ckan-kv-access
      containers:
      - name: ode-ckan # (1)
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m