apiVersion: apps/v1
kind: Deployment
metadata:
  name: odeckan
spec:
  selector:
    matchLabels:
      app: odeckan
  template:
    spec:
      volumes:
        - name: kvsecrets # (1)
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ode-ckan-dev-secretprovider
            nodePublishSecretRef:
              name: kvcreds