apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ode-ckan-dev-secretprovider
  namespace: ode-ckan-dev-ns
spec:
  provider: azure
  parameters:
    tenantId: 100b3c99-f3e2-4da0-9c8a-b9d345742c36
    subscriptionId: 4c231678-e100-4dd2-91cd-6aeb69e1dff8
    resourceGroup: datalake-k8s-rg-DEV
    keyvaultName: datalake-k8s-kv-dev-we
    # objects:  |
    #   array:
    #     - |
    #       objectName: odeckan-0
    #       objectAlias: ckan0_secret
    #       objectType: secret
    #     - |
    #       objectName: orstedca
    #       objectAlias: orstedca_secret
    #       objectType: secret
    #     - |
    #       objectName: ode-ckan-security-user-oidc-client-secret
    #       objectAlias: ode_ckan_security_user_oidc_client_secret
    #       objectType: secret
    #     - |
    #       objectName: ode-ckan-trust-store-password
    #       objectAlias: ode_ckan_trust_store_password
    #       objectType: secret
    #     - |
    #       objectName: ode-ckan-key-store-password
    #       objectAlias: ode_ckan_key_store_password
    #       objectType: secret
    #     - |
    #       objectName: ode-ckan-appinsights-key
    #       objectAlias: ode_ckan_appinsights_key
    #       objectType: secret
