apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odlckan
spec:
  template:
    spec:
      volumes:
        - name: kvsecrets # (1)
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: odl-ckan-dev-secretprovider
            nodePublishSecretRef:
              name: kvcreds