apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odeckan 
spec:
  template:
    spec:
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          nodePublishSecretRef:
            name: kvcreds
          readOnly: true
          volumeAttributes:
            secretProviderClass: "ode-ckan-dev-secretprovider"
        name: ckan-secrets