apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: odl-ckan-dev-secretprovider
  namespace: odl-ckan-dev-ns
spec:
  provider: azure
  parameters:
    tenantId: MISSSING
    subscriptionId: MISSING
    resourceGroup: DataLake-k8s-ckan-rg-DEV
    keyvaultName: odl-ckan-kv-dev-we  #TO BE CREATED
    objects:  |
      array:
        - |
          objectName: odlckan-0
          objectAlias: ckan0_secret
          objectType: secret
        - |
          objectName: orstedca
          objectAlias: orstedca_secret
          objectType: secret
        - |
          objectName: odl-ckan-security-user-oidc-client-secret
          objectAlias: odl_ckan_security_user_oidc_client_secret
          objectType: secret
        - |
          objectName: odl-ckan-trust-store-password
          objectAlias: odl_ckan_trust_store_password
          objectType: secret
        - |
          objectName: odl-ckan-key-store-password
          objectAlias: odl_ckan_key_store_password
          objectType: secret
        - |
          objectName: odl-ckan-appinsights-key
          objectAlias: odl_ckan_appinsights_key
          objectType: secret
