apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ode-ckan-dev-secretprovider
  namespace: ode-ckan-dev-ns
spec:
  parameters:
    keyvaultName: odl-ckan-kv-dev-we
    objects: |
      array:
        - |
          objectName: CKAN-SQLALCHEMY-URL
          objectAlias: sqlalchemy_alias
          objectType: secret
        - |
          objectName: ode-ckan-dev-ingress-tls
          objectAlias: ode_ckan_dev_ingress_tls
          objectType: secret
        - |
          objectName: CKAN-API-KEY
          objectAlias: CKAN_API_KEY
          objectType: secret
        - |
          objectName: CKAN-QUEUE-CONNECTIONSTRING
          objectAlias: CKAN_QUEUE_CONN_STRING
          objectType: secret
          
    resourceGroup: DataLake-k8s-ckan-rg-DEV
    subscriptionId: 4c231678-e100-4dd2-91cd-6aeb69e1dff8
    tenantId: 100b3c99-f3e2-4da0-9c8a-b9d345742c36
  provider: azure
  secretObjects:
  - data:
    - key: ode-ckan-dev-pg-conn-string
      objectName: sqlalchemy_alias
    secretName: ode-ckan-dev-secrets
    type: Opaque
  - data:
    - key: tls.key
      objectName: ode_ckan_dev_ingress_tls
    - key: tls.crt
      objectName: ode_ckan_dev_ingress_tls
    secretName: ode-ckan-dev-ingress-tls
    type: kubernetes.io/tls
