# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- resources/ckan-deployment.yaml
- resources/ckan-service.yaml
- resources/datapusher-deployment.yaml
- resources/datapusher-service.yaml
- resources/db-deployment.yaml
- resources/db-service.yaml
- resources/pg-data-pvc.yaml
- resources/redis-deployment.yaml
- resources/redis-service.yaml
- resources/solr-data-pvc.yaml
- resources/solr-deployment.yaml
- resources/solr-service.yaml
# namespace to deploy all Resources to
namespace: odl-ckan-sandbox-ns

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true

configMapGenerator:
- envs:
  - .env.template
  name: ckan-env-vars