# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- redis.yaml

# namespace to deploy all Resources to
namespace: tbd-in-overlays

images:
- name: ode-redis-image
  newName: redis
  # newName: datalakek8sacrdev.azurecr.io/ckan/redis
  # newTag: (version?)

commonLabels:
  app: oderedis
  env: tbd-in-overlays

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true
