---
apiVersion: v1
kind: Service
metadata:
  name: odlredis-hs
  labels:
    app: odlredis
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "socket"
      port: 6379
      targetPort: 6379
  selector:
    app: odlredis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: odlredis
  name: odlredis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odlredis
  serviceName: odlredis-hs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: odlredis
    spec:
      containers:
        - image: odl-redis-image
          name: odl-redis
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always

