---
apiVersion: v1
kind: Service
metadata:
  name: oderedis-service
  labels:
    app: oderedis
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "socket"
      port: 6379
      targetPort: 6379
  selector:
    app: oderedis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: oderedis
  name: oderedis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oderedis
  serviceName: oderedis-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oderedis
    spec:
      containers:
        - image: ode-redis-image
          name: ode-redis
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always

