---
apiVersion: v1
kind: Service
metadata:
  name: oderedis-service
  labels:
    app: oderedis
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: "socket"
      port: 6379
      targetPort: 6379
  selector:
    app: oderedis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oderedis
  name: oderedis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oderedis
  template:
    metadata:
      labels:
        app: oderedis
    spec:
      containers:
        - image: ode-redis-image
          name: ode-redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: socket
              protocol: TCP
          startupProbe:
            failureThreshold: 840
            periodSeconds: 30
            tcpSocket:
              port: socket
          readinessProbe:
            initialDelaySeconds: 840
            periodSeconds: 30
            timeoutSeconds: 30
            tcpSocket:
              port: socket
          livenessProbe:
            initialDelaySeconds: 840
            periodSeconds: 60
            tcpSocket:
              port: socket 
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always

